version: '3.8'
services:
    mysql:
      container_name: mysql
      image: mysql
      env_file: .env
      ports:
        - "3306:3306"
      volumes: 
        - ./mysql:/var/lib/mysql
      networks: 
        - chat-net

    chat-front:
      container_name: chat-front
      image: tronxi/chat-front:0.0.1_aes
      build: 
          context: https://github.com/tronxi/chat-front.git#master
          args:
              - ENVIRONMENT=docker
              - BRANCH=feature/aes
      ports:
          - "80:80"
      env_file: .env
      networks: 
          - chat-net

    chat-service:
        container_name: chat-service
        image: tronxi/chat-service:0.0.1
        build: 
            context: https://github.com/tronxi/chat-server.git#master
        ports:
            - "8080:8080"
        env_file: .env
        networks: 
            - chat-net

    chat-rabbit:
        container_name: chat-rabbit
        image: tronxi/rabbitmq-stomp:0.0.1
        build:
            context: ./rabbitmq/
        ports:
            - "15672:15672"
            - "5672:5672"
            - "61613:61613"
        env_file: .env
        networks: 
            - chat-net

    prometheus:
        container_name: prometheus
        image: prom/prometheus
        ports:
            - "9090:9090"
        volumes: 
            - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
        networks: 
            - chat-net
            
    grafana:
        container_name: grafana
        image: grafana/grafana
        ports:
            - "3000:3000"
        env_file: .env
        volumes: 
            - ./grafana/provisioning/:/etc/grafana/provisioning/
        networks:
            - chat-net

networks: 
    chat-net:
